# Generated by Django 4.2.13 on 2024-05-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.CharField(max_length=300)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
